name: "Dependabot"
on:
  schedule:
    - cron: "0 0 * * 1" # Every Monday at 00:00 UTC
  push:
    branches:
      - main

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7' # Specify the Ruby version here
      - name: Install Bundler
        run: gem install bundler
      - name: Install Dependabot Core
        run: |
          gem install dependabot-core
          gem install dependabot-common
      - name: Run Dependabot
        run: |
          bundle exec dependabot update --package-manager=pip --directory=/
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
