name: "Dependabot"
on:
  schedule:
    - cron: "0 0 * * 1" # Every Monday at 00:00 UTC
  push:
    branches:
      - main

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.8' # Specify the Ruby version here
      - name: Install Bundler
        run: gem install bundler -v 2.4.22
      - name: Install Dependencies
        run: bundle install
      - name: Run Dependabot
        run: |
          bundle exec ruby dependabot-script.rb
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
