name: "Dependabot"
on:
  schedule:
    - cron: "0 0 * * 1" # Every Monday at 00:00 UTC
  push:
    branches:
      - main

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
      - name: Install Dependabot
        run: gem install dependabot-cli
      - name: Run Dependabot
        run: |
          dependabot update --package-manager=pip --directory=/
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
